config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :auctions do
  resources :bids
end

resources :users, only: [:new, :create]

resources :sessions, only: [:new, :create] do
  delete :destroy, on: :collection
end

root 'auctions#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auction.rb
class Auction < ApplicationRecord
  belongs_to :user
  has_many :bids, dependent: :destroy

  validates :title, presence: true

  include AASM
  # draft / published / reserve met / won / canceled / reserve not met
    aasm do
    state :draft, initial: true
    state :published
    state :reserve_met
    state :won
    state :cancelled
    state :reserve_not_met

    event :publish do
      transitions from: :draft, to: :published
    end

    event :succeed do
      transitions from: :published, to: :reserve_met
    end

    event :fail_reserve do
      transitions from: :published, to: :reserve_not_met
    end

    event :winner do
      transitions from: :reserve_met, to: :won
    end

    event :cancel do
      transitions from: :published, to: :draft
    end
  end

end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :auction
  belongs_to :user
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true,
            format:  /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  def full_name
    "#{first_name} #{last_name}".squeeze(" ").strip.titleize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def user_signed_in?
    session[:user_id].present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authenticate_user!
    redirect_to new_session_path unless user_signed_in?
  end
  helper_method :authenticate_user!
  
  def auction_owner?(auction)
    current_user == auction.user
  end
  helper_method :auction_owner?
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  # before_action :authenticate_user!, only: [:create, :new]

  def index
    # @auctions = Auction.where(published: true)
    @auctions = Auction.all
  end

  def new
    @auction = Auction.new
  end

  def create
    @auction = Auction.new auction_params
    @auction.user = current_user
    if @auction.save
      redirect_to auction_path(@auction)
    else
      render :new
    end
  end

  def show
    @auction = Auction.find params[:id]
    @bid = Bid.new
    @bids = @auction.bids
  end

  def update
    @auction = Auction.find params[:id]
    if @auction.update auction_params
      redirect_to auction_path(@auction)
    end

    if @auction.publish!
      redirect_to @auction, notice: "Auction is published"
     else
       redirect_to @auction, notice: "Coudln't publish Auction"
     end


  end

  private

  def auction_params
    auction_params = params.require(:auction).permit(:title, :details, :ends_on, :reserve_price, :published)
  end

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def create
    @auction = Auction.find params[:auction_id]
    @bid = Bid.new bid_params
    @bid.auction = @auction
    @bid.user = current_user

    if @bid.amount > @auction.current_price
      @bid.save
      @auction.update(current_price: @bid.amount)
      redirect_to auction_path(@auction)
    else
      redirect_to auction_path(@auction)
    end

  end

  private

  def bid_params
    params.require(:bid).permit(:amount)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email params[:email]
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Logged in"
    else
      flash[:alert] = "Wrong email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Logged In!"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auctions/index.html.erb
<h1>Biddr</h1>
<% @auctions.each do |auction| %>
  <%= link_to "#{auction.title}", auction_path(auction) %>
  <hr>
<% end %>

app/views/auctions/new.html.erb
<h1>Create New Auction</h1>

<%= simple_form_for @auction do |f| %>
    <%= f.input :title, label: "Auction Item" %>
    <%= f.input :details %>
    <%= f.input :ends_on, :as => :datetime_picker %>
    <%= f.input :reserve_price %>
    <%= f.button :submit %>
<% end %>

app/views/auctions/show.html.erb
<h1><%= @auction.title %></h1>
<h2><%= @auction.details %></h2>

<h3>Auction Ends On:</h3><p><%= @auction.ends_on %></p>
<h3>Current Price:</h3><p> $<%= @auction.current_price %></p>
<h3>Reserve Price:</h3><p> $<%= @auction.reserve_price %></p>

<hr>

<% if !auction_owner?(@auction) %>
  <h2>Bid for this product</h2>
  <%= simple_form_for(@bid, url: auction_bids_path(@auction), method: :post) do |f| %>
    <%= f.input :amount %>
    <%= f.button :submit %>
  <% end %>
  <% else %>

  <%= link_to "Publish", auction_path(@auction),
                         class: "btn btn-primary btn-sm",
                         method: :patch,
                         data: { confirm: "Are you sure you want to publish" }
                         %>

<% end %>

<h2>Recent Bids</h2>

<% @bids.each do |bid| %>
  <%= bid.amount %>, by: <%= bid.user.first_name %>
  <hr>
<% end %>

app/views/bids/index.html.erb
bids index page

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Biddr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "All Auctions", auctions_path %>
    <% if user_signed_in? %>
      <%= link_to "Create New Auction", new_auction_path %>
      Hello <%= current_user.full_name %>,
      <%= link_to "Logout", sessions_path, method: :delete,
               data: {confirm: "are you sure you want to log out?"}%>
    <% else %>
      <%= link_to "Login", new_session_path %> |
      <%= link_to "Sign Up", new_user_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user do |f| %>
<div>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
</div>
<div>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
</div>
<div>
  <%= f.label :email %>
  <%= f.email_field :email %>
</div>
<div>
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>
<div>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div>
<%= f.submit %>
<% end %>